### PR TITLE
DRAFT Add support for the A4988 driver

### PR DESCRIPTION
**Pull request by shyndman**
This PR support for the [A4988] stepper driver.

As far as I can tell, everything's working great on actual hardware.

I tried to follow your lead for how to structure and document things, but let me know if I missed anything.

Thanks for the package!

DEPENDS on #145 being merged first.

[A4988]: https://www.allegromicro.com/en/products/motor-drivers/brush-dc-motor-drivers/a4988

### CODE REVIEW

**Review by hannobraun — APPROVED** [review]
Thank you, @shyndman! This one looks great too!

I can't find anything that you might have missed, CI is green, and you say it works great on hardware... good to go!

**Comment by hannobraun** [comment]
I've added a task to my list, to release a new version of Stepper, including your new crate. Given my workload these days, it might take me a minute to get to it though :smile:

**Comment by shyndman** [comment]
Thanks! I'm in zero rush.

I did actually find a bug in the step mode change flow — it's a mistake that I'm resetting the driver. I'll send a followup, tomorrow probably.

**Comment by hannobraun** [comment]
Sounds good, thank you!

**Pull request merged**
